### ISSUE TITLE
map_direction.jpg

### ISSUE THREAD

**Issue by kangmiao15** [SEU-zxj/LLM-Augmented-MTR#1]
Hello,

Thank you for this great work.

I was running "llm_augmented_prompt/tc_map/generate.py" for TC-Map generation and realized that it needs an image named "map_direction.jpg", but it's not shared in the repository. Can you upload it please?

**Comment by SEU-zxj** [comment]
Sorry for late reply and sorry for the missing of the image!

We have uploaded the image to this repo, you can access it at [llm_augmented_prompt/tools/agent_icons/map_direction](https://github.com/SEU-zxj/LLM-Augmented-MTR/blob/main/llm_augmented_prompt/tools/agent_icons/map_direction.jpg)

If you have further questions about this work, feel free to contact us!
